name: Build and publish bootrc os image

on:
  [workflow_dispatch]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: build image
          run: docker build ./images.fedora44 -t ${{ env.REGISTRY }}:latest
        - name: push image to docker hub
          run: docker push ${{ env.REGISTRY }}:latest
