FROM quay.io/fedora/fedora-bootc:44

# Base
RUN dnf install -y \
		bat \
		flatpak \
		fzf \
		kitty \
		zoxide \
		dnf5-plugins \
		zsh \
		neovim \
	&& dnf clean all

# Work
RUN dnf install -y \
		qemu \
		@virtualization \
		distrobox \
		podman \
	&& dnf clean all

# Desktop
RUN dnf copr enable -y avengemedia/dms \
	&& dnf install -y \
		niri \
		dms \
	&& systemctl --user add-wants niri.service dms \
	&& dnf clean all

RUN bootc container lint
