FROM quay.io/fedora/fedora-bootc:44

SHELL ["/bin/bash", "-c"]

RUN mkdir /tmp/packages
COPY packages/* /tmp/packages/

# Base
RUN dnf install -y \
		bat \
		flatpak \
		fzf \
		kitty \
		zoxide \
	&& dnf clean all

# Work
RUN dnf install -y \
		qemu \
		distrobox \
		podman \
	&& dnf clean all

# Desktop
RUN dnf copr enable -y avengemedia/dms \
	&& dnf install -y \
		niri \
		dms \
	&& dnf clean all

RUN bootc container init
